// InvoicesScreen.styles.js
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f8fafc',
    direction:"rtl"
  },
  statsContainer: {
    flexDirection: 'row',
    padding: 12,
    gap: 10,
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb',
  },
  statCard: {
    flex: 1,
    padding: 10,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: '#1e3a8a',
    backgroundColor: '#fff',
    alignItems: 'center',
  },
  statValue: {
    fontSize: 22,
    fontFamily: "IRANYekan",
    color: '#1e3a8a',
  },
  statLabel: {
    fontSize: 11,
    color: '#6b7280',
    marginTop: 2,
    fontFamily: "IRANYekan",
  },
  tabContainer: {
    flexDirection: 'row',
    backgroundColor: '#ffffff',
    marginHorizontal: 16,
    marginTop: 12,
    borderRadius: 8,
    padding: 4,
  },
  tab: {
    flex: 1,
    paddingVertical: 12,
    alignItems: 'center',
    borderRadius: 6,
  },
  activeTab: {
    backgroundColor: '#1e3a8a',
  },
  tabText: {
    fontSize: 13,
    fontFamily: "IRANYekan",
    color: '#6b7280',
  },
  activeTabText: {
    color: '#ffffff',
  },
  filterContainer: {
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  filterButton: {
    flexDirection: 'row',
    backgroundColor: '#ffffff',
    padding: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  filterButtonText: {
    color: '#1e3a8a',
    fontFamily: "IRANYekan",
    fontSize: 14,
  },
  listContent: {
    padding: 16,
    paddingBottom: 100,
  },
  invoiceRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#ffffff',
    padding: 16,
    borderRadius: 8,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  sentInvoiceRow: {
    backgroundColor: '#f0fdf4',
    borderColor: '#bbf7d0',
  },
  serverInvoiceRow: {
    backgroundColor: '#ffffff',
  },
  confirmedInvoiceRow: {
    backgroundColor: '#dbeafe',
    borderColor: '#93c5fd',
  },
  invoiceInfo: {
    flex: 1,
    paddingRight: 10,
  },
  customerHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  customerName: {
    fontSize: 16,
    fontFamily: "IRANYekan",
    color: '#1f2937',
    flex: 1,
  },
  locationBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#d1fae5',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    gap: 2,
  },
  locationText: {
    fontSize: 10,
    color: '#059669',
    fontFamily: "IRANYekan",
  },
  confirmedBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#dbeafe',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 4,
    gap: 4,
   
  },
  confirmedBadgeText: {
    fontSize: 10,
    color: '#1e3a8a',
    fontFamily: "IRANYekan",
  },
  pendingBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fef3c7',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 4,
    gap: 4,
  },
  pendingBadgeText: {
    fontSize: 10,
    color: '#f59e0b',
    fontFamily: "IRANYekan",
  },
  invoiceDetailsRow: {
    marginBottom: 6,
  },
  invoiceDetail: {
    fontSize: 14,
    color: '#6b7280',
    marginBottom: 2,
  },
  detailLabel: {
    fontFamily: "IRANYekan",
    color: '#513748ff',
  },
  sentText: {
    fontSize: 12,
    color: '#059669',
    fontFamily: "IRANYekan",
    marginTop: 4,
  },
  confirmedText: {
    fontSize: 12,
    color: '#1e3a8a',
    fontFamily: "IRANYekan",
    marginTop: 4,
  },
  pendingText: {
    fontSize: 12,
    color: '#f59e0b',
    fontFamily: "IRANYekan",
    marginTop: 4,
  },
  actionContainer: {
    marginLeft: 12,
  },
  actionsRow: {
    flexDirection: 'row',
    gap: 8,
  },
  sentActions: {
    alignItems: 'center',
    gap: 8,
  },
  actionButton: {
    width: 40,
    height: 40,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  editButton: {
    backgroundColor: 'transparent',
  },
  deleteButton: {
    backgroundColor: 'transparent',
  },
  sendButton: {
    backgroundColor: 'transparent',
  },
  sentBadge: {
    backgroundColor: '#dcfce7',
    color: '#166534',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 6,
    fontSize: 11,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  emptyState: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  emptyText: {
    fontSize: 16,
    color: '#6b7280',
    marginTop: 15,
    marginBottom: 20,
    textAlign: 'center',
    fontFamily: "IRANYekan",
  },
  addButton: {
    flexDirection: 'row',
    backgroundColor: '#1e3a8a',
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: 'center',
    gap: 8,
  },
  addButtonText: {
    color: '#ffffff',
    fontWeight: 'bold',
    fontSize: 16,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  loadingText: {
    marginTop: 12,
    fontSize: 14,
    color: '#6b7280',
    fontFamily: "IRANYekan",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  modalContent: {
    backgroundColor: 'white',
    borderRadius: 12,
    padding: 20,
    width: '100%',
    maxWidth: 400,
  },
  modalTitle: {
    fontSize: 18,
    fontFamily: "IRANYekan",
    marginBottom: 20,
    textAlign: 'center',
    color: '#1f2937',
  },
  quickActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginBottom: 20,
    gap: 10,
  },
  quickActionButton: {
    flex: 1,
    minWidth: '45%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#f8fafc',
    padding: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    gap: 8,
    marginBottom: 10,
  },
  quickActionText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#374151',
  },
  dateInputs: {
    marginBottom: 20,
  },
  dateInputContainer: {
    marginBottom: 15,
  },
  dateLabel: {
    fontSize: 14,
    fontFamily: "IRANYekan",
    marginBottom: 8,
    color: '#374151',
    textAlign: 'right',
  },
  dateInput: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#d1d5db',
    borderRadius: 8,
    padding: 12,
    backgroundColor: '#f9fafb',
  },
  dateInputText: {
    fontSize: 14,
    color: '#374151',
  },
  modalButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  modalButton: {
    flex: 1,
    padding: 12,
    borderRadius: 8,
    alignItems: 'center',
    marginHorizontal: 5,
  },
  cancelButton: {
    backgroundColor: '#f3f4f6',
    borderWidth: 1,
    borderColor: '#d1d5db',
  },
  applyButton: {
    backgroundColor: '#1e3a8a',
  },
  cancelButtonText: {
    color: '#374151',
    fontWeight: '600',
  },
  applyButtonText: {
    color: 'white',
    fontWeight: '600',
  },
  serverInvoiceContent: {
    flex: 1,
  },
  serverInvoiceHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 6,
  },
  serverInvoiceNumber: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#1e3a8a',
  },
  serverInvoiceAmount: {
    fontSize: 15,
    fontWeight: 'bold',
    color: '#059669',
  },
  serverInvoiceCustomer: {
    fontSize: 14,
    color: '#374151',
    marginBottom: 4,
  },
  serverInvoiceDate: {
    fontSize: 12,
    color: '#6b7280',
    marginBottom: 2,
  },
  invoiceDate:{
    fontFamily: "IRANYekan",
  },
  serverInvoiceStatus: {
    fontSize: 11,
    fontWeight: '600',
    marginTop: 4,
  },
});