import { Dimensions, StyleSheet } from 'react-native';

const { width, height } = Dimensions.get('window');

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f8fafc',
  },
  header: {
    backgroundColor: '#0622a3',
    paddingVertical: 20,
    paddingHorizontal: 15,
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  headerTitle: {
    color: 'white',
    fontSize: 22,
    fontWeight: 'bold',
    textAlign: 'center',
    fontFamily: 'IRANYekan',
    marginBottom: 5,
  },
  welcomeText: {
    color: 'rgba(255,255,255,0.9)',
    fontSize: 14,
    textAlign: 'center',
    fontFamily: 'IRANYekan',
  },
  customerSelection: {
    backgroundColor: 'white',
    padding: 20,
    marginHorizontal: 15,
    marginTop: 20,
    borderRadius: 15,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
    elevation: 5,
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  selectionTitle: {
    fontSize: 14,
    color: '#64748b',
    marginBottom: 12,
    fontFamily: 'IRANYekan',
    textAlign: 'right',
  },
  selectCustomerButton: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: '#e2e8f0',
    borderRadius: 12,
    padding: 15,
    backgroundColor: '#f8fafc',
  },
  selectCustomerText: {
    fontSize: 16,
    color: '#334155',
    fontFamily: 'IRANYekan',
    textAlign: 'right',
    flex: 1,
  },
  tabContainer: {
    flexDirection: 'row',
    backgroundColor: 'white',
    marginHorizontal: 15,
    marginTop: 20,
    borderRadius: 15,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 4,
    borderWidth: 1,
    borderColor: '#f1f5f9',
  },
  tab: {
    flex: 1,
    paddingVertical: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  activeTab: {
    backgroundColor: '#0622a3',
  },
  tabText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#64748b',
    fontFamily: 'IRANYekan',
  },
  activeTabText: {
    color: 'white',
  },
  content: {
    flex: 1,
    padding: 15,
  },
  orderItem: {
    backgroundColor: 'white',
    borderRadius: 15,
    padding: 18,
    marginBottom: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 3,
    borderWidth: 1,
    borderColor: '#f1f5f9',
  },
  orderHeader: {
    flex: 1,
  },
  orderNumber: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#1e293b',
    marginBottom: 6,
    fontFamily: 'IRANYekan',
    textAlign: 'right',
  },
  orderDate: {
    fontSize: 13,
    color: '#64748b',
    fontFamily: 'IRANYekan',
    textAlign: 'right',
  },
  orderDetails: {
    alignItems: 'flex-end',
    marginLeft: 10,
  },
  priceRow: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    marginBottom: 4,
  },
  priceLabel: {
    fontSize: 12,
    color: '#64748b',
    marginRight: 6,
    fontFamily: 'IRANYekan',
  },
  priceValue: {
    fontSize: 13,
    fontWeight: 'bold',
    color: '#1e293b',
    fontFamily: 'IRANYekan',
  },
  returnBadge: {
    backgroundColor: '#fef2f2',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
    marginTop: 6,
    borderWidth: 1,
    borderColor: '#fecaca',
  },
  returnBadgeText: {
    fontSize: 11,
    color: '#dc2626',
    fontWeight: 'bold',
    fontFamily: 'IRANYekan',
    textAlign: 'center',
  },
  orderArrow: {
    marginRight: 5,
  },
  modalContainer: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.6)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  modalContent: {
    backgroundColor: 'white',
    borderRadius: 20,
    width: width * 0.9,
    maxHeight: height * 0.8,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.3,
    shadowRadius: 20,
    elevation: 10,
  },
  modalHeader: {
    flexDirection: 'row-reverse',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9',
    backgroundColor: '#f8fafc',
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#1e293b',
    fontFamily: 'IRANYekan',
    textAlign: 'right',
  },
  closeButton: {
    padding: 5,
  },
  detailsList: {
    padding: 15,
  },
  detailItem: {
    backgroundColor: '#f8fafc',
    borderRadius: 12,
    padding: 16,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  detailHeader: {
    flexDirection: 'row-reverse',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 12,
  },
  productName: {
    fontSize: 15,
    fontWeight: 'bold',
    color: '#1e293b',
    flex: 1,
    fontFamily: 'IRANYekan',
    textAlign: 'right',
    lineHeight: 22,
  },
  productCode: {
    fontSize: 12,
    color: '#64748b',
    fontFamily: 'IRANYekan',
    textAlign: 'right',
    marginRight: 10,
  },
  detailRow: {
    flexDirection: 'row-reverse',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  detailLabel: {
    fontSize: 13,
    color: '#64748b',
    fontFamily: 'IRANYekan',
    textAlign: 'right',
  },
  detailValue: {
    fontSize: 13,
    fontWeight: '600',
    color: '#1e293b',
    fontFamily: 'IRANYekan',
    textAlign: 'left',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#f8fafc',
  },
  loadingText: {
    marginTop: 15,
    fontSize: 16,
    color: '#64748b',
    fontFamily: 'IRANYekan',
    textAlign: 'center',
  },
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 60,
  },
  emptyText: {
    marginTop: 15,
    fontSize: 16,
    color: '#94a3b8',
    fontFamily: 'IRANYekan',
    textAlign: 'center',
  },
  // استایل‌های مدال انتخاب مشتری
  customerModalContainer: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.6)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  customerModalContent: {
    backgroundColor: 'white',
    borderRadius: 20,
    width: width * 0.9,
    height: height * 0.7,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.3,
    shadowRadius: 20,
    elevation: 10,
  },
  customerModalHeader: {
    flexDirection: 'row-reverse',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9',
    backgroundColor: '#0622a3',
  },
  customerModalTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: 'white',
    fontFamily: 'IRANYekan',
    textAlign: 'right',
  },
  searchContainer: {
    padding: 15,
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9',
  },
  searchInput: {
    backgroundColor: '#f8fafc',
    borderWidth: 1.5,
    borderColor: '#e2e8f0',
    borderRadius: 12,
    padding: 15,
    fontSize: 16,
    fontFamily: 'IRANYekan',
    textAlign: 'right',
    color: '#334155',
  },
  customerList: {
    flex: 1,
  },
  customerItem: {
    flexDirection: 'row-reverse',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 18,
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9',
  },
  customerInfo: {
    flex: 1,
  },
  customerName: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1e293b',
    fontFamily: 'IRANYekan',
    textAlign: 'right',
    marginBottom: 4,
  },
  customerCode: {
    fontSize: 13,
    color: '#64748b',
    fontFamily: 'IRANYekan',
    textAlign: 'right',
  },
  selectButton: {
    backgroundColor: '#0622a3',
    paddingHorizontal: 20,
    paddingVertical: 8,
    borderRadius: 10,
    marginRight: 10,
  },
  selectButtonText: {
    color: 'white',
    fontSize: 12,
    fontWeight: 'bold',
    fontFamily: 'IRANYekan',
  },
  noCustomersText: {
    textAlign: 'center',
    color: '#94a3b8',
    fontSize: 16,
    fontFamily: 'IRANYekan',
    marginTop: 50,
  },
  // در styles/OrderReportScreen.styles.js اضافه کنید:

// استایل برای تب پرداخت‌ها
balanceTab: {
  flex: 1,
  paddingVertical: 16,
  alignItems: 'center',
  justifyContent: 'center',
},
activeBalanceTab: {
  backgroundColor: '#059669', // سبز برای پرداخت‌ها
},
balanceTabText: {
  fontSize: 14,
  fontWeight: '600',
  color: '#64748b',
  fontFamily: 'IRANYekan',
},
activeBalanceTabText: {
  color: 'white',
},

// استایل برای نمایش مانده حساب
balanceContainer: {
  backgroundColor: 'white',
  padding: 20,
  marginHorizontal: 15,
  marginBottom: 15,
  borderRadius: 15,
  shadowColor: '#000',
  shadowOffset: { width: 0, height: 3 },
  shadowOpacity: 0.1,
  shadowRadius: 6,
  elevation: 4,
  borderWidth: 1,
  borderColor: '#f1f5f9',
},
balanceTitle: {
  fontSize: 16,
  fontWeight: 'bold',
  color: '#1e293b',
  fontFamily: 'IRANYekan',
  textAlign: 'center',
  marginBottom: 10,
},
balanceAmount: {
  fontSize: 24,
  fontWeight: 'bold',
  textAlign: 'center',
  fontFamily: 'IRANYekan',
},
positiveBalance: {
  color: '#dc2626', // قرمز برای مانده مثبت (بدهکار)
},
negativeBalance: {
  color: '#059669', // سبز برای مانده منفی (بستانکار)
},
zeroBalance: {
  color: '#64748b', // خاکستری برای صفر
},

// استایل برای آیتم‌های پرداخت
paymentItem: {
  backgroundColor: 'white',
  borderRadius: 15,
  padding: 18,
  marginBottom: 12,
  shadowColor: '#000',
  shadowOffset: { width: 0, height: 2 },
  shadowOpacity: 0.08,
  shadowRadius: 4,
  elevation: 3,
  borderWidth: 1,
  borderColor: '#f1f5f9',
},
paymentHeader: {
  flexDirection: 'row-reverse',
  justifyContent: 'space-between',
  alignItems: 'center',
  marginBottom: 10,
},
paymentDate: {
  fontSize: 14,
  color: '#64748b',
  fontFamily: 'IRANYekan',
  textAlign: 'right',
},
paymentType: {
  fontSize: 12,
  fontWeight: 'bold',
  color: 'white',
  paddingHorizontal: 8,
  paddingVertical: 4,
  borderRadius: 6,
  fontFamily: 'IRANYekan',
},
debitType: {
  backgroundColor: '#dc2626', // قرمز برای بدهکار
},
creditType: {
  backgroundColor: '#059669', // سبز برای بستانکار
},


paymentDetails: {
  flexDirection: 'row-reverse',
  justifyContent: 'space-between',
  alignItems: 'center',
},
paymentAmount: {
  fontSize: 16,
  fontWeight: 'bold',
  fontFamily: 'IRANYekan',
},
debitAmount: {
  color: '#dc2626', // قرمز برای بدهکار
},

creditAmount: {
  color: '#059669', // سبز برای بستانکار
},
paymentDescription: {
  fontSize: 13,
  color: '#64748b',
  fontFamily: 'IRANYekan',
  textAlign: 'right',
  flex: 1,
  marginRight: 10,
},
});